"use client";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";

export default function Home() {
  const router = useRouter();
  return (
    <main className="h-screen w-full mx-auto my-0 text-center flex flex-col justify-between">
      <nav className="flex flex-row items-center justify-between mx-4 mt-2">
        <div className="flex flex-row items-center justify-between gap-4">
          <h1 className="font-bold text-lg">ProFlow</h1>
          <div className="flex flex-row gap-2">
            <a
              href="https://www.github.com/adidevs/proflow"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-blue-600 cursor-pointer"
            >
              GitHub
            </a>
          </div>
        </div>
        <div className="flex flex-row items-center justify-between gap-2">
          <Button
            onClick={() => router.push("/sign-in")}
            variant="outline"
            className="hover:bg-gray-200"
          >
            Log In
          </Button>
          <Button
            onClick={() => router.push("/sign-in")}
            className="bg-blue-500 hover:bg-blue-700"
          >
            Sign Up
          </Button>
        </div>
      </nav>

      {/* Main Content */}
      <div className="flex flex-col items-center justify-center flex-grow mx-4">
        <h1 className="text-3xl font-semibold my-4 mt-14">
          Welcome to ProFlow!
        </h1>
        <p className="text-lg">
          ProFlow is a project management tool that helps you manage your
          projects with ease.
        </p>
        <p className="text-lg mb-4">Get started by logging in or signing up!</p>
        <div className="flex flex-row gap-2 mt-4">
          <Button
            onClick={() => router.push("/app/today")}
            className="bg-blue-500 hover:bg-blue-700"
          >
            Get Started
          </Button>
        </div>

        {/* Features Section */}
        <section className="mt-8">
          <h2 className="text-2xl text-center font-bold mb-6">Features</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-8 mt-6">
            <div className="p-6 border border-gray-200 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
              <h3 className="text-xl font-semibold mb-2">Task Management</h3>
              <p className="text-gray-700">
                Create tasks, assign them to team members, and track their
                progress.
              </p>
            </div>
            <div className="p-6 border border-gray-200 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
              <h3 className="text-xl font-semibold mb-2">Organize with AI</h3>
              <p className="text-gray-700">
                Create projects and initialize them with tasks generated by
                Google Gemini, add further tasks to them, and manage your
                team&apos;s workflow.
              </p>
            </div>
            <div className="p-6 border border-gray-200 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
              <h3 className="text-xl font-semibold mb-2">Collaborate</h3>
              <p className="text-gray-700">
                Add team members to your projects, assign tasks to them, and
                collaborate with ease.
              </p>
            </div>
            <div className="p-6 border border-gray-200 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
              <h3 className="text-xl font-semibold mb-2">Kanban Board</h3>
              <p className="text-gray-700">
                Visualize your tasks in a kanban board, move them across
                columns, and track their progress.
              </p>
            </div>
          </div>
        </section>
      </div>

      {/* Footer */}
      <div className=" my-5 w-full text-center text-gray-600">
        Made with Next.js, TypeScript & ❤️ by Aditya Sharma
      </div>
    </main>
  );
}
